{{- range .Values.inferenceObjectives }}
---
apiVersion: llm-d.ai/v1alpha2
kind: InferenceObjective
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "llm-d-inference-scheduler.labels" $ | nindent 4 }}
spec:
  priority: {{ .priority }}
  poolRef:
    group: {{ .Values.inferenceExtension.poolGroup | default "inference.networking.k8s.io" }}
    name: {{ $.Release.Name }}
{{- end }}
