# ------------------------------------------------------------------------------
# Custom Resource Definitions (CRDs) for Gateway API Inference Extension (GIE)
#
# **Warning**: CRDs are cluster-level, so in a shared development environment
# this needs to be done in a controlled and communicated manner.
#
# These files are copied from the pinned GIE Go module by `make sync-upstream-crds`.
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- inference.networking.k8s.io_inferencepools.yaml
- inference.networking.x-k8s.io_inferencepoolimports.yaml
