{{ include "llm-d-router.validations.epp" $ }}
{{ include "llm-d-router.validations.standalone" . }}
{{ include "llm-d-router.config" . }}
{{ include "llm-d-router.deployment" . }}
{{ include "llm-d-router.gke" . }}
{{ include "llm-d-router.lead-election-rbac" . }}
{{ include "llm-d-router.sa-token-secret" . }}
{{ include "llm-d-router.service" . }}
{{ include "llm-d-router.service-monitor" . }}
{{ include "llm-d-router.rbac" . }}
{{ include "llm-d-router.inferencepool-resource" . }}
