{{- define "inference-extension.sa-token-secret" -}}
{{- $inferenceExtensionMonitoringProviderName := include "llm-d-inference-scheduler.inferenceExtension.monitoring.provider.name" . | lower -}}
{{- if and .Values.inferenceExtension.monitoring.prometheus.enabled .Values.inferenceExtension.monitoring.prometheus.auth.enabled (eq $inferenceExtensionMonitoringProviderName "prometheusoperator") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.inferenceExtension.monitoring.prometheus.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-d-inference-scheduler.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "llm-d-inference-scheduler.name" . }}
type: kubernetes.io/service-account-token
---
{{- end }}
{{- end }}
