/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hack/telemetry.sh from the Weaver registry. DO NOT EDIT.

package semconv

import "go.opentelemetry.io/otel/attribute"

// Custom llm-d router trace attributes.
const (
	// LLMDCoordinatorPipelineExecutionPathKey: The step combination a request took.
	LLMDCoordinatorPipelineExecutionPathKey = attribute.Key("llm_d.coordinator.pipeline.execution_path")
	// LLMDCoordinatorPipelineStepCountKey: The number of steps configured in the pipeline.
	LLMDCoordinatorPipelineStepCountKey = attribute.Key("llm_d.coordinator.pipeline.step_count")
	// LLMDECProxyEncodeDisaggregationUsedKey: Whether encode disaggregation was used.
	LLMDECProxyEncodeDisaggregationUsedKey = attribute.Key("llm_d.ec_proxy.encode_disaggregation_used")
	// LLMDECProxyEncoderCandidatesKey: Candidate encoder count in EC proxy.
	LLMDECProxyEncoderCandidatesKey = attribute.Key("llm_d.ec_proxy.encoder_candidates")
	// LLMDECProxyEncoderCountKey: Allowed encoder count in EC proxy.
	LLMDECProxyEncoderCountKey = attribute.Key("llm_d.ec_proxy.encoder_count")
	// LLMDEPPDisaggReasonKey: Disaggregation reason.
	LLMDEPPDisaggReasonKey = attribute.Key("llm_d.epp.disagg.reason")
	// LLMDEPPEncodeDisaggregationUsedKey: Whether encode disaggregation was used.
	LLMDEPPEncodeDisaggregationUsedKey = attribute.Key("llm_d.epp.encode.disaggregation_used")
	// LLMDEPPEncodeEndpointsKey: Encode endpoints.
	LLMDEPPEncodeEndpointsKey = attribute.Key("llm_d.epp.encode.endpoints")
	// LLMDEPPEncodeReasonKey: Encode disaggregation reason.
	LLMDEPPEncodeReasonKey = attribute.Key("llm_d.epp.encode.reason")
	// LLMDEPPFairnessIDKey: The resolved fairness identity.
	// Always paired with llm_d.epp.fairness.source.
	LLMDEPPFairnessIDKey = attribute.Key("llm_d.epp.fairness.id")
	// LLMDEPPFairnessSourceKey: How the fairness identity was resolved.
	// The value header does not establish that the producer was authenticated.
	LLMDEPPFairnessSourceKey = attribute.Key("llm_d.epp.fairness.source")
	// LLMDEPPFilterAffinityThresholdKey: The configured prefix cache affinity threshold.
	LLMDEPPFilterAffinityThresholdKey = attribute.Key("llm_d.epp.filter.affinity_threshold")
	// LLMDEPPFilterCandidateEndpointsKey: The number of endpoints a filter received.
	LLMDEPPFilterCandidateEndpointsKey = attribute.Key("llm_d.epp.filter.candidate_endpoints")
	// LLMDEPPFilterDecisionKey: The outcome a filter decided on.
	LLMDEPPFilterDecisionKey = attribute.Key("llm_d.epp.filter.decision")
	// LLMDEPPFilterFilteredEndpointsKey: The number of endpoints a filter returned.
	LLMDEPPFilterFilteredEndpointsKey = attribute.Key("llm_d.epp.filter.filtered_endpoints")
	// LLMDEPPFilterStickyEndpointsKey: The number of endpoints meeting the affinity threshold.
	LLMDEPPFilterStickyEndpointsKey = attribute.Key("llm_d.epp.filter.sticky_endpoints")
	// LLMDEPPFilterTTFTPenaltyMsKey: The TTFT penalty the load gate measured, in milliseconds.
	LLMDEPPFilterTTFTPenaltyMsKey = attribute.Key("llm_d.epp.filter.ttft_penalty_ms")
	// LLMDEPPPDDisaggregationUsedKey: Whether PD disaggregation was used.
	LLMDEPPPDDisaggregationUsedKey = attribute.Key("llm_d.epp.pd.disaggregation_used")
	// LLMDEPPPDPrefillPodAddressKey: Selected prefill pod address.
	LLMDEPPPDPrefillPodAddressKey = attribute.Key("llm_d.epp.pd.prefill_pod_address")
	// LLMDEPPPDPrefillPodPortKey: Selected prefill pod port.
	LLMDEPPPDPrefillPodPortKey = attribute.Key("llm_d.epp.pd.prefill_pod_port")
	// LLMDEPPPDReasonKey: Prefill/decode disaggregation reason.
	LLMDEPPPDReasonKey = attribute.Key("llm_d.epp.pd.reason")
	// LLMDEPPPickerCandidateEndpointsKey: Candidate endpoints entering the picker.
	LLMDEPPPickerCandidateEndpointsKey = attribute.Key("llm_d.epp.picker.candidate_endpoints")
	// LLMDEPPPickerTopEndpointsKey: The top scored endpoint names.
	LLMDEPPPickerTopEndpointsKey = attribute.Key("llm_d.epp.picker.top_endpoints")
	// LLMDEPPPickerTopScoresKey: The top scored endpoint values.
	LLMDEPPPickerTopScoresKey = attribute.Key("llm_d.epp.picker.top_scores")
	// LLMDEPPProducerCandidateEndpointsKey: Producer candidate endpoints count.
	LLMDEPPProducerCandidateEndpointsKey = attribute.Key("llm_d.epp.producer.candidate_endpoints")
	// LLMDEPPProducerMaxMatchBlocksKey: Max matched blocks in producer.
	LLMDEPPProducerMaxMatchBlocksKey = attribute.Key("llm_d.epp.producer.max_match_blocks")
	// LLMDEPPProducerResultKey: Producer result.
	LLMDEPPProducerResultKey = attribute.Key("llm_d.epp.producer.result")
	// LLMDEPPProducerTotalBlocksKey: Total blocks in producer.
	LLMDEPPProducerTotalBlocksKey = attribute.Key("llm_d.epp.producer.total_blocks")
	// LLMDEPPProfileHandlerDecisionKey: The profile handler decision.
	LLMDEPPProfileHandlerDecisionKey = attribute.Key("llm_d.epp.profile_handler.decision")
	// LLMDEPPProfileHandlerDecodeFailedKey: Whether decode execution failed.
	LLMDEPPProfileHandlerDecodeFailedKey = attribute.Key("llm_d.epp.profile_handler.decode_failed")
	// LLMDEPPProfileHandlerExecutedProfilesKey: Executed profiles count.
	LLMDEPPProfileHandlerExecutedProfilesKey = attribute.Key("llm_d.epp.profile_handler.executed_profiles")
	// LLMDEPPProfileHandlerPrefillFailedKey: Whether a required prefill execution failed.
	LLMDEPPProfileHandlerPrefillFailedKey = attribute.Key("llm_d.epp.profile_handler.prefill_failed")
	// LLMDEPPProfileHandlerSelectedProfileKey: The selected profile name.
	LLMDEPPProfileHandlerSelectedProfileKey = attribute.Key("llm_d.epp.profile_handler.selected_profile")
	// LLMDEPPProfileHandlerTotalProfilesKey: Total profiles evaluated.
	LLMDEPPProfileHandlerTotalProfilesKey = attribute.Key("llm_d.epp.profile_handler.total_profiles")
	// LLMDEPPProfileNameKey: The scheduled profile name.
	LLMDEPPProfileNameKey = attribute.Key("llm_d.epp.scheduling.profile.name")
	// LLMDEPPScorerCandidateEndpointsKey: The number of candidate endpoints for a scorer.
	LLMDEPPScorerCandidateEndpointsKey = attribute.Key("llm_d.epp.scorer.candidate_endpoints")
	// LLMDEPPScorerCountKey: The number of scorers configured in a profile.
	LLMDEPPScorerCountKey = attribute.Key("llm_d.epp.scorer.count")
	// LLMDEPPScorerEndpointsScoredKey: The number of endpoints scored.
	LLMDEPPScorerEndpointsScoredKey = attribute.Key("llm_d.epp.scorer.endpoints_scored")
	// LLMDEPPScorerNameKey: The EPP scorer instance name.
	LLMDEPPScorerNameKey = attribute.Key("llm_d.epp.scorer.name")
	// LLMDEPPScorerScoreAvgKey: The average score generated by a scorer.
	LLMDEPPScorerScoreAvgKey = attribute.Key("llm_d.epp.scorer.score.avg")
	// LLMDEPPScorerScoreMaxKey: The maximum score generated by a scorer.
	LLMDEPPScorerScoreMaxKey = attribute.Key("llm_d.epp.scorer.score.max")
	// LLMDEPPScorerTypeKey: The EPP scorer type.
	LLMDEPPScorerTypeKey = attribute.Key("llm_d.epp.scorer.type")
	// LLMDEPPScorerWeightKey: The EPP scorer weight.
	LLMDEPPScorerWeightKey = attribute.Key("llm_d.epp.scorer.weight")
	// LLMDEPPScoringCandidateEndpointsKey: Candidate endpoints entering the scorer chain.
	LLMDEPPScoringCandidateEndpointsKey = attribute.Key("llm_d.epp.scoring.candidate_endpoints")
	// LLMDEPPTokenProducerBackendKey: Token producer backend.
	LLMDEPPTokenProducerBackendKey = attribute.Key("llm_d.epp.token_producer.backend")
	// LLMDEPPTokenProducerResultKey: Token producer result.
	LLMDEPPTokenProducerResultKey = attribute.Key("llm_d.epp.token_producer.result")
	// LLMDEPPTokenProducerTokenCountKey: Token producer token count.
	LLMDEPPTokenProducerTokenCountKey = attribute.Key("llm_d.epp.token_producer.token_count")
	// LLMDKVCacheBlockHitRatioKey: KV cache block hit ratio.
	LLMDKVCacheBlockHitRatioKey = attribute.Key("llm_d.kv_cache.block_hit_ratio")
	// LLMDKVCacheBlockKeysCountKey: KV cache block keys count.
	LLMDKVCacheBlockKeysCountKey = attribute.Key("llm_d.kv_cache.block_keys.count")
	// LLMDKVCacheBlocksFoundKey: KV cache blocks found.
	LLMDKVCacheBlocksFoundKey = attribute.Key("llm_d.kv_cache.blocks_found")
	// LLMDKVCacheEventsEventCountKey: KV cache event batch count.
	LLMDKVCacheEventsEventCountKey = attribute.Key("llm_d.kv_cache.events.event_count")
	// LLMDKVCacheEventsPayloadSizeBytesKey: KV cache event payload size.
	LLMDKVCacheEventsPayloadSizeBytesKey = attribute.Key("llm_d.kv_cache.events.payload_size_bytes")
	// LLMDKVCacheEventsPodIDKey: KV cache event pod ID.
	LLMDKVCacheEventsPodIDKey = attribute.Key("llm_d.kv_cache.events.pod_id")
	// LLMDKVCacheEventsSequenceKey: KV cache event sequence.
	LLMDKVCacheEventsSequenceKey = attribute.Key("llm_d.kv_cache.events.sequence")
	// LLMDKVCacheEventsSourceEndpointKey: KV cache event source endpoint.
	LLMDKVCacheEventsSourceEndpointKey = attribute.Key("llm_d.kv_cache.events.source_endpoint")
	// LLMDKVCacheEventsTopicKey: KV cache event topic.
	LLMDKVCacheEventsTopicKey = attribute.Key("llm_d.kv_cache.events.topic")
	// LLMDKVCacheIndexAddDeviceTierCountKey: KV cache index add device tiers count.
	LLMDKVCacheIndexAddDeviceTierCountKey = attribute.Key("llm_d.kv_cache.index.add.device_tier_count")
	// LLMDKVCacheIndexAddEngineKeyCountKey: KV cache index add engine keys count.
	LLMDKVCacheIndexAddEngineKeyCountKey = attribute.Key("llm_d.kv_cache.index.add.engine_key_count")
	// LLMDKVCacheIndexAddPodEntryCountKey: KV cache index add pod entries count.
	LLMDKVCacheIndexAddPodEntryCountKey = attribute.Key("llm_d.kv_cache.index.add.pod_entry_count")
	// LLMDKVCacheIndexAddRequestKeyCountKey: KV cache index add request keys count.
	LLMDKVCacheIndexAddRequestKeyCountKey = attribute.Key("llm_d.kv_cache.index.add.request_key_count")
	// LLMDKVCacheIndexEvictDeviceTierCountKey: KV cache index evicted device tiers count.
	LLMDKVCacheIndexEvictDeviceTierCountKey = attribute.Key("llm_d.kv_cache.index.evict.device_tier_count")
	// LLMDKVCacheIndexEvictKeyCountKey: KV cache index evicted keys count.
	LLMDKVCacheIndexEvictKeyCountKey = attribute.Key("llm_d.kv_cache.index.evict.key_count")
	// LLMDKVCacheIndexEvictKeyTypeKey: KV cache index evicted key type.
	LLMDKVCacheIndexEvictKeyTypeKey = attribute.Key("llm_d.kv_cache.index.evict.key_type")
	// LLMDKVCacheIndexEvictPodEntryCountKey: KV cache index evicted pod entries count.
	LLMDKVCacheIndexEvictPodEntryCountKey = attribute.Key("llm_d.kv_cache.index.evict.pod_entry_count")
	// LLMDKVCacheIndexLookupBlockCountKey: KV cache index lookup block count.
	LLMDKVCacheIndexLookupBlockCountKey = attribute.Key("llm_d.kv_cache.index.lookup.block_count")
	// LLMDKVCacheIndexWalkKeyCountKey: KV cache index walk key count.
	LLMDKVCacheIndexWalkKeyCountKey = attribute.Key("llm_d.kv_cache.index.walk.key_count")
	// LLMDKVCacheIndexWalkKeysPresentKey: KV cache index walk keys present.
	LLMDKVCacheIndexWalkKeysPresentKey = attribute.Key("llm_d.kv_cache.index.walk.keys_present")
	// LLMDKVCacheLookupBlocksFoundKey: KV cache lookup blocks found.
	LLMDKVCacheLookupBlocksFoundKey = attribute.Key("llm_d.kv_cache.lookup.blocks_found")
	// LLMDKVCacheLookupCacheHitKey: KV cache lookup cache hit.
	LLMDKVCacheLookupCacheHitKey = attribute.Key("llm_d.kv_cache.lookup.cache_hit")
	// LLMDKVCacheLookupPodFilterCountKey: KV cache lookup pod filter count.
	LLMDKVCacheLookupPodFilterCountKey = attribute.Key("llm_d.kv_cache.lookup.pod_filter_count")
	// LLMDKVCachePodCountKey: KV cache pod count.
	LLMDKVCachePodCountKey = attribute.Key("llm_d.kv_cache.pod_count")
	// LLMDKVCachePrefixMatchKeyCountKey: Prefix match key count.
	LLMDKVCachePrefixMatchKeyCountKey = attribute.Key("llm_d.kv_cache.prefix_match.key_count")
	// LLMDKVCachePrefixMatchLongestChainKey: Prefix match longest block chain.
	LLMDKVCachePrefixMatchLongestChainKey = attribute.Key("llm_d.kv_cache.prefix_match.longest_chain")
	// LLMDKVCachePrefixMatchPodFilterCountKey: Prefix match pod filter count.
	LLMDKVCachePrefixMatchPodFilterCountKey = attribute.Key("llm_d.kv_cache.prefix_match.pod_filter_count")
	// LLMDKVCachePrefixMatchPodsMatchedKey: Prefix match matched pods count.
	LLMDKVCachePrefixMatchPodsMatchedKey = attribute.Key("llm_d.kv_cache.prefix_match.pods_matched")
	// LLMDKVCachePrefixMatchWalkedKey: Whether key walker was used.
	LLMDKVCachePrefixMatchWalkedKey = attribute.Key("llm_d.kv_cache.prefix_match.walked")
	// LLMDKVCacheTokenCountKey: KV cache token count.
	LLMDKVCacheTokenCountKey = attribute.Key("llm_d.kv_cache.token_count")
	// LLMDOpenAIAPIKey: OpenAI API endpoint type.
	LLMDOpenAIAPIKey = attribute.Key("llm_d.openai.api")
	// LLMDPDProxyBootstrapRoomKey: The SGLang P/D bootstrap room ID.
	LLMDPDProxyBootstrapRoomKey = attribute.Key("llm_d.pd_proxy.bootstrap_room")
	// LLMDPDProxyChunkedDecodeChunkSizeKey: Chunked decode chunk size.
	LLMDPDProxyChunkedDecodeChunkSizeKey = attribute.Key("llm_d.pd_proxy.chunked_decode.chunk_size")
	// LLMDPDProxyChunkedDecodeChunksKey: Number of chunks in chunked decode.
	LLMDPDProxyChunkedDecodeChunksKey = attribute.Key("llm_d.pd_proxy.chunked_decode.chunks")
	// LLMDPDProxyChunkedDecodeDurationMsKey: Chunked decode duration in milliseconds.
	LLMDPDProxyChunkedDecodeDurationMsKey = attribute.Key("llm_d.pd_proxy.chunked_decode.duration_ms")
	// LLMDPDProxyChunkedDecodeStreamingKey: Whether chunked decode was streaming.
	LLMDPDProxyChunkedDecodeStreamingKey = attribute.Key("llm_d.pd_proxy.chunked_decode.streaming")
	// LLMDPDProxyChunkedDecodeTotalTokensKey: Total tokens in chunked decode.
	LLMDPDProxyChunkedDecodeTotalTokensKey = attribute.Key("llm_d.pd_proxy.chunked_decode.total_tokens")
	// LLMDPDProxyConcurrentPDKey: Whether concurrent PD was used.
	LLMDPDProxyConcurrentPDKey = attribute.Key("llm_d.pd_proxy.concurrent_pd")
	// LLMDPDProxyConnectorKey: PD proxy connector name.
	LLMDPDProxyConnectorKey = attribute.Key("llm_d.pd_proxy.connector")
	// LLMDPDProxyCoordinatorOverheadMsKey: Coordinator overhead in milliseconds.
	LLMDPDProxyCoordinatorOverheadMsKey = attribute.Key("llm_d.pd_proxy.coordinator_overhead_ms")
	// LLMDPDProxyDecodeConcurrentWithPrefillKey: Whether decode ran concurrently with prefill.
	LLMDPDProxyDecodeConcurrentWithPrefillKey = attribute.Key("llm_d.pd_proxy.decode.concurrent_with_prefill")
	// LLMDPDProxyDecodeDataParallelKey: Whether decode used data parallel.
	LLMDPDProxyDecodeDataParallelKey = attribute.Key("llm_d.pd_proxy.decode.data_parallel")
	// LLMDPDProxyDecodeDurationMsKey: Decode span duration in milliseconds.
	LLMDPDProxyDecodeDurationMsKey = attribute.Key("llm_d.pd_proxy.decode.duration_ms")
	// LLMDPDProxyDecodeStreamingKey: Whether decode used streaming.
	LLMDPDProxyDecodeStreamingKey = attribute.Key("llm_d.pd_proxy.decode.streaming")
	// LLMDPDProxyDecodeTargetKey: PD proxy decode target host/port.
	LLMDPDProxyDecodeTargetKey = attribute.Key("llm_d.pd_proxy.decode.target")
	// LLMDPDProxyDecodeDurationMsSummaryKey: Summary decode duration in milliseconds.
	LLMDPDProxyDecodeDurationMsSummaryKey = attribute.Key("llm_d.pd_proxy.decode_duration_ms")
	// LLMDPDProxyDeniedTargetKey: PD proxy denied target address.
	LLMDPDProxyDeniedTargetKey = attribute.Key("llm_d.pd_proxy.denied_target")
	// LLMDPDProxyDisaggregationUsedKey: Whether PD proxy disaggregation was used.
	LLMDPDProxyDisaggregationUsedKey = attribute.Key("llm_d.pd_proxy.disaggregation_used")
	// LLMDPDProxyECConnectorKey: PD proxy EC connector name.
	LLMDPDProxyECConnectorKey = attribute.Key("llm_d.pd_proxy.ec_connector")
	// LLMDPDProxyErrorKey: PD proxy error classification.
	LLMDPDProxyErrorKey = attribute.Key("llm_d.pd_proxy.error")
	// LLMDPDProxyKVCacheSourceKey: PD proxy KV cache source header value.
	LLMDPDProxyKVCacheSourceKey = attribute.Key("llm_d.pd_proxy.kv_cache_source")
	// LLMDPDProxyKVConnectorKey: PD proxy KV connector name.
	LLMDPDProxyKVConnectorKey = attribute.Key("llm_d.pd_proxy.kv_connector")
	// LLMDPDProxyParallelDispatchKey: Whether parallel dispatch was used.
	LLMDPDProxyParallelDispatchKey = attribute.Key("llm_d.pd_proxy.parallel_dispatch")
	// LLMDPDProxyParallelWindowMsKey: PD proxy parallel window in milliseconds.
	LLMDPDProxyParallelWindowMsKey = attribute.Key("llm_d.pd_proxy.parallel_window_ms")
	// LLMDPDProxyPrefillAsyncKey: Whether prefill was asynchronous.
	LLMDPDProxyPrefillAsyncKey = attribute.Key("llm_d.pd_proxy.prefill.async")
	// LLMDPDProxyPrefillDurationMsKey: Prefill span duration in milliseconds.
	LLMDPDProxyPrefillDurationMsKey = attribute.Key("llm_d.pd_proxy.prefill.duration_ms")
	// LLMDPDProxyPrefillStatusCodeKey: Prefill HTTP response status code.
	LLMDPDProxyPrefillStatusCodeKey = attribute.Key("llm_d.pd_proxy.prefill.status_code")
	// LLMDPDProxyPrefillCandidatesKey: PD proxy prefill candidate count.
	LLMDPDProxyPrefillCandidatesKey = attribute.Key("llm_d.pd_proxy.prefill_candidates")
	// LLMDPDProxyPrefillDurationMsSummaryKey: Summary prefill duration in milliseconds.
	LLMDPDProxyPrefillDurationMsSummaryKey = attribute.Key("llm_d.pd_proxy.prefill_duration_ms")
	// LLMDPDProxyPrefillTargetKey: PD proxy prefill target host/port.
	LLMDPDProxyPrefillTargetKey = attribute.Key("llm_d.pd_proxy.prefill_target")
	// LLMDPDProxyReasonKey: PD proxy decision reason.
	LLMDPDProxyReasonKey = attribute.Key("llm_d.pd_proxy.reason")
	// LLMDPDProxyRequestIDKey: PD proxy request ID.
	LLMDPDProxyRequestIDKey = attribute.Key("llm_d.pd_proxy.request_id")
	// LLMDPDProxyRequestPathKey: PD proxy request path.
	LLMDPDProxyRequestPathKey = attribute.Key("llm_d.pd_proxy.request_path")
	// LLMDPDProxyTotalDurationMsKey: PD proxy total duration in milliseconds.
	LLMDPDProxyTotalDurationMsKey = attribute.Key("llm_d.pd_proxy.total_duration_ms")
	// LLMDPDProxyTrueTTFTMsKey: PD proxy true TTFT in milliseconds.
	LLMDPDProxyTrueTTFTMsKey = attribute.Key("llm_d.pd_proxy.true_ttft_ms")
)

// LLMDCoordinatorPipelineExecutionPath: The step combination a request took.
func LLMDCoordinatorPipelineExecutionPath(value string) attribute.KeyValue {
	return LLMDCoordinatorPipelineExecutionPathKey.String(value)
}

// LLMDCoordinatorPipelineStepCount: The number of steps configured in the pipeline.
func LLMDCoordinatorPipelineStepCount(value int) attribute.KeyValue {
	return LLMDCoordinatorPipelineStepCountKey.Int(value)
}

// LLMDECProxyEncodeDisaggregationUsed: Whether encode disaggregation was used.
func LLMDECProxyEncodeDisaggregationUsed(value bool) attribute.KeyValue {
	return LLMDECProxyEncodeDisaggregationUsedKey.Bool(value)
}

// LLMDECProxyEncoderCandidates: Candidate encoder count in EC proxy.
func LLMDECProxyEncoderCandidates(value int) attribute.KeyValue {
	return LLMDECProxyEncoderCandidatesKey.Int(value)
}

// LLMDECProxyEncoderCount: Allowed encoder count in EC proxy.
func LLMDECProxyEncoderCount(value int) attribute.KeyValue {
	return LLMDECProxyEncoderCountKey.Int(value)
}

// LLMDEPPDisaggReason: Disaggregation reason.
func LLMDEPPDisaggReason(value string) attribute.KeyValue {
	return LLMDEPPDisaggReasonKey.String(value)
}

// LLMDEPPEncodeDisaggregationUsed: Whether encode disaggregation was used.
func LLMDEPPEncodeDisaggregationUsed(value bool) attribute.KeyValue {
	return LLMDEPPEncodeDisaggregationUsedKey.Bool(value)
}

// LLMDEPPEncodeEndpoints: Encode endpoints.
func LLMDEPPEncodeEndpoints(value string) attribute.KeyValue {
	return LLMDEPPEncodeEndpointsKey.String(value)
}

// LLMDEPPEncodeReason: Encode disaggregation reason.
func LLMDEPPEncodeReason(value string) attribute.KeyValue {
	return LLMDEPPEncodeReasonKey.String(value)
}

// LLMDEPPFairnessID: The resolved fairness identity.
func LLMDEPPFairnessID(value string) attribute.KeyValue {
	return LLMDEPPFairnessIDKey.String(value)
}

// LLMDEPPFairnessSource: How the fairness identity was resolved.
func LLMDEPPFairnessSource(value string) attribute.KeyValue {
	return LLMDEPPFairnessSourceKey.String(value)
}

// LLMDEPPFilterAffinityThreshold: The configured prefix cache affinity threshold.
func LLMDEPPFilterAffinityThreshold(value float64) attribute.KeyValue {
	return LLMDEPPFilterAffinityThresholdKey.Float64(value)
}

// LLMDEPPFilterCandidateEndpoints: The number of endpoints a filter received.
func LLMDEPPFilterCandidateEndpoints(value int) attribute.KeyValue {
	return LLMDEPPFilterCandidateEndpointsKey.Int(value)
}

// LLMDEPPFilterDecision: The outcome a filter decided on.
func LLMDEPPFilterDecision(value string) attribute.KeyValue {
	return LLMDEPPFilterDecisionKey.String(value)
}

// LLMDEPPFilterFilteredEndpoints: The number of endpoints a filter returned.
func LLMDEPPFilterFilteredEndpoints(value int) attribute.KeyValue {
	return LLMDEPPFilterFilteredEndpointsKey.Int(value)
}

// LLMDEPPFilterStickyEndpoints: The number of endpoints meeting the affinity threshold.
func LLMDEPPFilterStickyEndpoints(value int) attribute.KeyValue {
	return LLMDEPPFilterStickyEndpointsKey.Int(value)
}

// LLMDEPPFilterTTFTPenaltyMs: The TTFT penalty the load gate measured, in milliseconds.
func LLMDEPPFilterTTFTPenaltyMs(value float64) attribute.KeyValue {
	return LLMDEPPFilterTTFTPenaltyMsKey.Float64(value)
}

// LLMDEPPPDDisaggregationUsed: Whether PD disaggregation was used.
func LLMDEPPPDDisaggregationUsed(value bool) attribute.KeyValue {
	return LLMDEPPPDDisaggregationUsedKey.Bool(value)
}

// LLMDEPPPDPrefillPodAddress: Selected prefill pod address.
func LLMDEPPPDPrefillPodAddress(value string) attribute.KeyValue {
	return LLMDEPPPDPrefillPodAddressKey.String(value)
}

// LLMDEPPPDPrefillPodPort: Selected prefill pod port.
func LLMDEPPPDPrefillPodPort(value string) attribute.KeyValue {
	return LLMDEPPPDPrefillPodPortKey.String(value)
}

// LLMDEPPPDReason: Prefill/decode disaggregation reason.
func LLMDEPPPDReason(value string) attribute.KeyValue {
	return LLMDEPPPDReasonKey.String(value)
}

// LLMDEPPPickerCandidateEndpoints: Candidate endpoints entering the picker.
func LLMDEPPPickerCandidateEndpoints(value int) attribute.KeyValue {
	return LLMDEPPPickerCandidateEndpointsKey.Int(value)
}

// LLMDEPPPickerTopEndpoints: The top scored endpoint names.
func LLMDEPPPickerTopEndpoints(value []string) attribute.KeyValue {
	return LLMDEPPPickerTopEndpointsKey.StringSlice(value)
}

// LLMDEPPPickerTopScores: The top scored endpoint values.
func LLMDEPPPickerTopScores(value []float64) attribute.KeyValue {
	return LLMDEPPPickerTopScoresKey.Float64Slice(value)
}

// LLMDEPPProducerCandidateEndpoints: Producer candidate endpoints count.
func LLMDEPPProducerCandidateEndpoints(value int) attribute.KeyValue {
	return LLMDEPPProducerCandidateEndpointsKey.Int(value)
}

// LLMDEPPProducerMaxMatchBlocks: Max matched blocks in producer.
func LLMDEPPProducerMaxMatchBlocks(value int) attribute.KeyValue {
	return LLMDEPPProducerMaxMatchBlocksKey.Int(value)
}

// LLMDEPPProducerResult: Producer result.
func LLMDEPPProducerResult(value string) attribute.KeyValue {
	return LLMDEPPProducerResultKey.String(value)
}

// LLMDEPPProducerTotalBlocks: Total blocks in producer.
func LLMDEPPProducerTotalBlocks(value int) attribute.KeyValue {
	return LLMDEPPProducerTotalBlocksKey.Int(value)
}

// LLMDEPPProfileHandlerDecision: The profile handler decision.
func LLMDEPPProfileHandlerDecision(value string) attribute.KeyValue {
	return LLMDEPPProfileHandlerDecisionKey.String(value)
}

// LLMDEPPProfileHandlerDecodeFailed: Whether decode execution failed.
func LLMDEPPProfileHandlerDecodeFailed(value bool) attribute.KeyValue {
	return LLMDEPPProfileHandlerDecodeFailedKey.Bool(value)
}

// LLMDEPPProfileHandlerExecutedProfiles: Executed profiles count.
func LLMDEPPProfileHandlerExecutedProfiles(value int) attribute.KeyValue {
	return LLMDEPPProfileHandlerExecutedProfilesKey.Int(value)
}

// LLMDEPPProfileHandlerPrefillFailed: Whether a required prefill execution failed.
func LLMDEPPProfileHandlerPrefillFailed(value bool) attribute.KeyValue {
	return LLMDEPPProfileHandlerPrefillFailedKey.Bool(value)
}

// LLMDEPPProfileHandlerSelectedProfile: The selected profile name.
func LLMDEPPProfileHandlerSelectedProfile(value string) attribute.KeyValue {
	return LLMDEPPProfileHandlerSelectedProfileKey.String(value)
}

// LLMDEPPProfileHandlerTotalProfiles: Total profiles evaluated.
func LLMDEPPProfileHandlerTotalProfiles(value int) attribute.KeyValue {
	return LLMDEPPProfileHandlerTotalProfilesKey.Int(value)
}

// LLMDEPPProfileName: The scheduled profile name.
func LLMDEPPProfileName(value string) attribute.KeyValue {
	return LLMDEPPProfileNameKey.String(value)
}

// LLMDEPPScorerCandidateEndpoints: The number of candidate endpoints for a scorer.
func LLMDEPPScorerCandidateEndpoints(value int) attribute.KeyValue {
	return LLMDEPPScorerCandidateEndpointsKey.Int(value)
}

// LLMDEPPScorerCount: The number of scorers configured in a profile.
func LLMDEPPScorerCount(value int) attribute.KeyValue {
	return LLMDEPPScorerCountKey.Int(value)
}

// LLMDEPPScorerEndpointsScored: The number of endpoints scored.
func LLMDEPPScorerEndpointsScored(value int) attribute.KeyValue {
	return LLMDEPPScorerEndpointsScoredKey.Int(value)
}

// LLMDEPPScorerName: The EPP scorer instance name.
func LLMDEPPScorerName(value string) attribute.KeyValue {
	return LLMDEPPScorerNameKey.String(value)
}

// LLMDEPPScorerScoreAvg: The average score generated by a scorer.
func LLMDEPPScorerScoreAvg(value float64) attribute.KeyValue {
	return LLMDEPPScorerScoreAvgKey.Float64(value)
}

// LLMDEPPScorerScoreMax: The maximum score generated by a scorer.
func LLMDEPPScorerScoreMax(value float64) attribute.KeyValue {
	return LLMDEPPScorerScoreMaxKey.Float64(value)
}

// LLMDEPPScorerType: The EPP scorer type.
func LLMDEPPScorerType(value string) attribute.KeyValue {
	return LLMDEPPScorerTypeKey.String(value)
}

// LLMDEPPScorerWeight: The EPP scorer weight.
func LLMDEPPScorerWeight(value float64) attribute.KeyValue {
	return LLMDEPPScorerWeightKey.Float64(value)
}

// LLMDEPPScoringCandidateEndpoints: Candidate endpoints entering the scorer chain.
func LLMDEPPScoringCandidateEndpoints(value int) attribute.KeyValue {
	return LLMDEPPScoringCandidateEndpointsKey.Int(value)
}

// LLMDEPPTokenProducerBackend: Token producer backend.
func LLMDEPPTokenProducerBackend(value string) attribute.KeyValue {
	return LLMDEPPTokenProducerBackendKey.String(value)
}

// LLMDEPPTokenProducerResult: Token producer result.
func LLMDEPPTokenProducerResult(value string) attribute.KeyValue {
	return LLMDEPPTokenProducerResultKey.String(value)
}

// LLMDEPPTokenProducerTokenCount: Token producer token count.
func LLMDEPPTokenProducerTokenCount(value int) attribute.KeyValue {
	return LLMDEPPTokenProducerTokenCountKey.Int(value)
}

// LLMDKVCacheBlockHitRatio: KV cache block hit ratio.
func LLMDKVCacheBlockHitRatio(value float64) attribute.KeyValue {
	return LLMDKVCacheBlockHitRatioKey.Float64(value)
}

// LLMDKVCacheBlockKeysCount: KV cache block keys count.
func LLMDKVCacheBlockKeysCount(value int) attribute.KeyValue {
	return LLMDKVCacheBlockKeysCountKey.Int(value)
}

// LLMDKVCacheBlocksFound: KV cache blocks found.
func LLMDKVCacheBlocksFound(value int) attribute.KeyValue {
	return LLMDKVCacheBlocksFoundKey.Int(value)
}

// LLMDKVCacheEventsEventCount: KV cache event batch count.
func LLMDKVCacheEventsEventCount(value int) attribute.KeyValue {
	return LLMDKVCacheEventsEventCountKey.Int(value)
}

// LLMDKVCacheEventsPayloadSizeBytes: KV cache event payload size.
func LLMDKVCacheEventsPayloadSizeBytes(value int) attribute.KeyValue {
	return LLMDKVCacheEventsPayloadSizeBytesKey.Int(value)
}

// LLMDKVCacheEventsPodID: KV cache event pod ID.
func LLMDKVCacheEventsPodID(value string) attribute.KeyValue {
	return LLMDKVCacheEventsPodIDKey.String(value)
}

// LLMDKVCacheEventsSequence: KV cache event sequence.
func LLMDKVCacheEventsSequence(value int64) attribute.KeyValue {
	return LLMDKVCacheEventsSequenceKey.Int64(value)
}

// LLMDKVCacheEventsSourceEndpoint: KV cache event source endpoint.
func LLMDKVCacheEventsSourceEndpoint(value string) attribute.KeyValue {
	return LLMDKVCacheEventsSourceEndpointKey.String(value)
}

// LLMDKVCacheEventsTopic: KV cache event topic.
func LLMDKVCacheEventsTopic(value string) attribute.KeyValue {
	return LLMDKVCacheEventsTopicKey.String(value)
}

// LLMDKVCacheIndexAddDeviceTierCount: KV cache index add device tiers count.
func LLMDKVCacheIndexAddDeviceTierCount(value int) attribute.KeyValue {
	return LLMDKVCacheIndexAddDeviceTierCountKey.Int(value)
}

// LLMDKVCacheIndexAddEngineKeyCount: KV cache index add engine keys count.
func LLMDKVCacheIndexAddEngineKeyCount(value int) attribute.KeyValue {
	return LLMDKVCacheIndexAddEngineKeyCountKey.Int(value)
}

// LLMDKVCacheIndexAddPodEntryCount: KV cache index add pod entries count.
func LLMDKVCacheIndexAddPodEntryCount(value int) attribute.KeyValue {
	return LLMDKVCacheIndexAddPodEntryCountKey.Int(value)
}

// LLMDKVCacheIndexAddRequestKeyCount: KV cache index add request keys count.
func LLMDKVCacheIndexAddRequestKeyCount(value int) attribute.KeyValue {
	return LLMDKVCacheIndexAddRequestKeyCountKey.Int(value)
}

// LLMDKVCacheIndexEvictDeviceTierCount: KV cache index evicted device tiers count.
func LLMDKVCacheIndexEvictDeviceTierCount(value int) attribute.KeyValue {
	return LLMDKVCacheIndexEvictDeviceTierCountKey.Int(value)
}

// LLMDKVCacheIndexEvictKeyCount: KV cache index evicted keys count.
func LLMDKVCacheIndexEvictKeyCount(value int) attribute.KeyValue {
	return LLMDKVCacheIndexEvictKeyCountKey.Int(value)
}

// LLMDKVCacheIndexEvictKeyType: KV cache index evicted key type.
func LLMDKVCacheIndexEvictKeyType(value string) attribute.KeyValue {
	return LLMDKVCacheIndexEvictKeyTypeKey.String(value)
}

// LLMDKVCacheIndexEvictPodEntryCount: KV cache index evicted pod entries count.
func LLMDKVCacheIndexEvictPodEntryCount(value int) attribute.KeyValue {
	return LLMDKVCacheIndexEvictPodEntryCountKey.Int(value)
}

// LLMDKVCacheIndexLookupBlockCount: KV cache index lookup block count.
func LLMDKVCacheIndexLookupBlockCount(value int) attribute.KeyValue {
	return LLMDKVCacheIndexLookupBlockCountKey.Int(value)
}

// LLMDKVCacheIndexWalkKeyCount: KV cache index walk key count.
func LLMDKVCacheIndexWalkKeyCount(value int) attribute.KeyValue {
	return LLMDKVCacheIndexWalkKeyCountKey.Int(value)
}

// LLMDKVCacheIndexWalkKeysPresent: KV cache index walk keys present.
func LLMDKVCacheIndexWalkKeysPresent(value int) attribute.KeyValue {
	return LLMDKVCacheIndexWalkKeysPresentKey.Int(value)
}

// LLMDKVCacheLookupBlocksFound: KV cache lookup blocks found.
func LLMDKVCacheLookupBlocksFound(value int) attribute.KeyValue {
	return LLMDKVCacheLookupBlocksFoundKey.Int(value)
}

// LLMDKVCacheLookupCacheHit: KV cache lookup cache hit.
func LLMDKVCacheLookupCacheHit(value bool) attribute.KeyValue {
	return LLMDKVCacheLookupCacheHitKey.Bool(value)
}

// LLMDKVCacheLookupPodFilterCount: KV cache lookup pod filter count.
func LLMDKVCacheLookupPodFilterCount(value int) attribute.KeyValue {
	return LLMDKVCacheLookupPodFilterCountKey.Int(value)
}

// LLMDKVCachePodCount: KV cache pod count.
func LLMDKVCachePodCount(value int) attribute.KeyValue {
	return LLMDKVCachePodCountKey.Int(value)
}

// LLMDKVCachePrefixMatchKeyCount: Prefix match key count.
func LLMDKVCachePrefixMatchKeyCount(value int) attribute.KeyValue {
	return LLMDKVCachePrefixMatchKeyCountKey.Int(value)
}

// LLMDKVCachePrefixMatchLongestChain: Prefix match longest block chain.
func LLMDKVCachePrefixMatchLongestChain(value int) attribute.KeyValue {
	return LLMDKVCachePrefixMatchLongestChainKey.Int(value)
}

// LLMDKVCachePrefixMatchPodFilterCount: Prefix match pod filter count.
func LLMDKVCachePrefixMatchPodFilterCount(value int) attribute.KeyValue {
	return LLMDKVCachePrefixMatchPodFilterCountKey.Int(value)
}

// LLMDKVCachePrefixMatchPodsMatched: Prefix match matched pods count.
func LLMDKVCachePrefixMatchPodsMatched(value int) attribute.KeyValue {
	return LLMDKVCachePrefixMatchPodsMatchedKey.Int(value)
}

// LLMDKVCachePrefixMatchWalked: Whether key walker was used.
func LLMDKVCachePrefixMatchWalked(value bool) attribute.KeyValue {
	return LLMDKVCachePrefixMatchWalkedKey.Bool(value)
}

// LLMDKVCacheTokenCount: KV cache token count.
func LLMDKVCacheTokenCount(value int) attribute.KeyValue {
	return LLMDKVCacheTokenCountKey.Int(value)
}

// LLMDOpenAIAPI: OpenAI API endpoint type.
func LLMDOpenAIAPI(value string) attribute.KeyValue {
	return LLMDOpenAIAPIKey.String(value)
}

// LLMDPDProxyBootstrapRoom: The SGLang P/D bootstrap room ID.
func LLMDPDProxyBootstrapRoom(value int64) attribute.KeyValue {
	return LLMDPDProxyBootstrapRoomKey.Int64(value)
}

// LLMDPDProxyChunkedDecodeChunkSize: Chunked decode chunk size.
func LLMDPDProxyChunkedDecodeChunkSize(value int) attribute.KeyValue {
	return LLMDPDProxyChunkedDecodeChunkSizeKey.Int(value)
}

// LLMDPDProxyChunkedDecodeChunks: Number of chunks in chunked decode.
func LLMDPDProxyChunkedDecodeChunks(value int) attribute.KeyValue {
	return LLMDPDProxyChunkedDecodeChunksKey.Int(value)
}

// LLMDPDProxyChunkedDecodeDurationMs: Chunked decode duration in milliseconds.
func LLMDPDProxyChunkedDecodeDurationMs(value float64) attribute.KeyValue {
	return LLMDPDProxyChunkedDecodeDurationMsKey.Float64(value)
}

// LLMDPDProxyChunkedDecodeStreaming: Whether chunked decode was streaming.
func LLMDPDProxyChunkedDecodeStreaming(value bool) attribute.KeyValue {
	return LLMDPDProxyChunkedDecodeStreamingKey.Bool(value)
}

// LLMDPDProxyChunkedDecodeTotalTokens: Total tokens in chunked decode.
func LLMDPDProxyChunkedDecodeTotalTokens(value int) attribute.KeyValue {
	return LLMDPDProxyChunkedDecodeTotalTokensKey.Int(value)
}

// LLMDPDProxyConcurrentPD: Whether concurrent PD was used.
func LLMDPDProxyConcurrentPD(value bool) attribute.KeyValue {
	return LLMDPDProxyConcurrentPDKey.Bool(value)
}

// LLMDPDProxyConnector: PD proxy connector name.
func LLMDPDProxyConnector(value string) attribute.KeyValue {
	return LLMDPDProxyConnectorKey.String(value)
}

// LLMDPDProxyCoordinatorOverheadMs: Coordinator overhead in milliseconds.
func LLMDPDProxyCoordinatorOverheadMs(value float64) attribute.KeyValue {
	return LLMDPDProxyCoordinatorOverheadMsKey.Float64(value)
}

// LLMDPDProxyDecodeConcurrentWithPrefill: Whether decode ran concurrently with prefill.
func LLMDPDProxyDecodeConcurrentWithPrefill(value bool) attribute.KeyValue {
	return LLMDPDProxyDecodeConcurrentWithPrefillKey.Bool(value)
}

// LLMDPDProxyDecodeDataParallel: Whether decode used data parallel.
func LLMDPDProxyDecodeDataParallel(value bool) attribute.KeyValue {
	return LLMDPDProxyDecodeDataParallelKey.Bool(value)
}

// LLMDPDProxyDecodeDurationMs: Decode span duration in milliseconds.
func LLMDPDProxyDecodeDurationMs(value float64) attribute.KeyValue {
	return LLMDPDProxyDecodeDurationMsKey.Float64(value)
}

// LLMDPDProxyDecodeStreaming: Whether decode used streaming.
func LLMDPDProxyDecodeStreaming(value bool) attribute.KeyValue {
	return LLMDPDProxyDecodeStreamingKey.Bool(value)
}

// LLMDPDProxyDecodeTarget: PD proxy decode target host/port.
func LLMDPDProxyDecodeTarget(value string) attribute.KeyValue {
	return LLMDPDProxyDecodeTargetKey.String(value)
}

// LLMDPDProxyDecodeDurationMsSummary: Summary decode duration in milliseconds.
func LLMDPDProxyDecodeDurationMsSummary(value float64) attribute.KeyValue {
	return LLMDPDProxyDecodeDurationMsSummaryKey.Float64(value)
}

// LLMDPDProxyDeniedTarget: PD proxy denied target address.
func LLMDPDProxyDeniedTarget(value string) attribute.KeyValue {
	return LLMDPDProxyDeniedTargetKey.String(value)
}

// LLMDPDProxyDisaggregationUsed: Whether PD proxy disaggregation was used.
func LLMDPDProxyDisaggregationUsed(value bool) attribute.KeyValue {
	return LLMDPDProxyDisaggregationUsedKey.Bool(value)
}

// LLMDPDProxyECConnector: PD proxy EC connector name.
func LLMDPDProxyECConnector(value string) attribute.KeyValue {
	return LLMDPDProxyECConnectorKey.String(value)
}

// LLMDPDProxyError: PD proxy error classification.
func LLMDPDProxyError(value string) attribute.KeyValue {
	return LLMDPDProxyErrorKey.String(value)
}

// LLMDPDProxyKVCacheSource: PD proxy KV cache source header value.
func LLMDPDProxyKVCacheSource(value string) attribute.KeyValue {
	return LLMDPDProxyKVCacheSourceKey.String(value)
}

// LLMDPDProxyKVConnector: PD proxy KV connector name.
func LLMDPDProxyKVConnector(value string) attribute.KeyValue {
	return LLMDPDProxyKVConnectorKey.String(value)
}

// LLMDPDProxyParallelDispatch: Whether parallel dispatch was used.
func LLMDPDProxyParallelDispatch(value bool) attribute.KeyValue {
	return LLMDPDProxyParallelDispatchKey.Bool(value)
}

// LLMDPDProxyParallelWindowMs: PD proxy parallel window in milliseconds.
func LLMDPDProxyParallelWindowMs(value float64) attribute.KeyValue {
	return LLMDPDProxyParallelWindowMsKey.Float64(value)
}

// LLMDPDProxyPrefillAsync: Whether prefill was asynchronous.
func LLMDPDProxyPrefillAsync(value bool) attribute.KeyValue {
	return LLMDPDProxyPrefillAsyncKey.Bool(value)
}

// LLMDPDProxyPrefillDurationMs: Prefill span duration in milliseconds.
func LLMDPDProxyPrefillDurationMs(value float64) attribute.KeyValue {
	return LLMDPDProxyPrefillDurationMsKey.Float64(value)
}

// LLMDPDProxyPrefillStatusCode: Prefill HTTP response status code.
func LLMDPDProxyPrefillStatusCode(value int) attribute.KeyValue {
	return LLMDPDProxyPrefillStatusCodeKey.Int(value)
}

// LLMDPDProxyPrefillCandidates: PD proxy prefill candidate count.
func LLMDPDProxyPrefillCandidates(value int) attribute.KeyValue {
	return LLMDPDProxyPrefillCandidatesKey.Int(value)
}

// LLMDPDProxyPrefillDurationMsSummary: Summary prefill duration in milliseconds.
func LLMDPDProxyPrefillDurationMsSummary(value float64) attribute.KeyValue {
	return LLMDPDProxyPrefillDurationMsSummaryKey.Float64(value)
}

// LLMDPDProxyPrefillTarget: PD proxy prefill target host/port.
func LLMDPDProxyPrefillTarget(value string) attribute.KeyValue {
	return LLMDPDProxyPrefillTargetKey.String(value)
}

// LLMDPDProxyReason: PD proxy decision reason.
func LLMDPDProxyReason(value string) attribute.KeyValue {
	return LLMDPDProxyReasonKey.String(value)
}

// LLMDPDProxyRequestID: PD proxy request ID.
func LLMDPDProxyRequestID(value string) attribute.KeyValue {
	return LLMDPDProxyRequestIDKey.String(value)
}

// LLMDPDProxyRequestPath: PD proxy request path.
func LLMDPDProxyRequestPath(value string) attribute.KeyValue {
	return LLMDPDProxyRequestPathKey.String(value)
}

// LLMDPDProxyTotalDurationMs: PD proxy total duration in milliseconds.
func LLMDPDProxyTotalDurationMs(value float64) attribute.KeyValue {
	return LLMDPDProxyTotalDurationMsKey.Float64(value)
}

// LLMDPDProxyTrueTTFTMs: PD proxy true TTFT in milliseconds.
func LLMDPDProxyTrueTTFTMs(value float64) attribute.KeyValue {
	return LLMDPDProxyTrueTTFTMsKey.Float64(value)
}
