/*
Copyright 2026 The llm-d Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hack/telemetry.sh from the Weaver registry. DO NOT EDIT.

package semconv

const (
	// LLMDEPPSpanFilterEndpoints: Applies the filter chain to candidate endpoints.
	LLMDEPPSpanFilterEndpoints = "filter_endpoints"
	// LLMDEPPSpanPickEndpoints: Selects an endpoint from the scored candidates.
	LLMDEPPSpanPickEndpoints = "pick_endpoints"
	// LLMDEPPSpanRunSchedulerProfile: Runs one named scheduler profile.
	LLMDEPPSpanRunSchedulerProfile = "run_scheduler_profile"
	// LLMDEPPSpanScoring: Combines weighted scores from the configured scorers.
	LLMDEPPSpanScoring = "scoring"
)
